---
apiVersion: v1
kind: Secret
data:
  # Replace this with your own secret, `pwgen -s 64 1 | base64 -w0` helps
  auth-secret: TVcxNmpKZHZOWm1SUmpneGNDdm0yWGxCRnFqMXc1ZVBXR1VpRjRGNzdFbVBqMnZGU2dZbXpBd0lrejNhdEN4ZAo=
metadata:
  labels:
    app: bcoturn
  name: bcoturn-secret
  namespace: bcoturn-ns
type: Opaque