apiVersion: v1
kind: Service
metadata:
  labels:
    app: bcoturn
  name: bcoturn
  namespace: bcoturn-ns
spec:
  ports:
  # You can't currently have both UDP and TCP in the same LoadBalancer on K8s,
  # so if you need both you'll have to have two LoadBalancer services.
  - name: udp-port
    port: 3487
    protocol: TCP
    targetPort: 3487
  selector:
    app: bcoturn
  type: LoadBalancer